name: Deploy React
on:
  push:
    branches:
      # - home
      - main
      - features/**
      - "!features/authen"
  workflow_dispatch:
  pull_request:
    types:
      - opened

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: oven/bun:1
      env: 
        NODE_ENV: production
    steps:
      - name: Use repo variable
        run: echo "API URL:${{ vars.API_VARIABLE }}"
      - name: Use repo secrets
        run: echo "API URL:${{ secrets.API_SECRET }}"
      - name: Clone repo
        uses: actions/checkout@v5        
      - name: Install and Cacshe
        uses: .github/actions/install-cache
      - name: Build Project
        run: bun run build
      - name: List files
        run: ls -l dist
      - name: Upload dist folder
        uses: actions/upload-artifact@v4
        with:
          name: dist-folder
          path: dist/

  deploy:
    # if: ${{github.ref == 'refs/heads/main'}}
    if: success()
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download dist folder
        uses: actions/download-artifact@v4
        with:
          name: dist-folder
      - name: List all files
        run: ls -R
      - name: Deploy
        run: echo "Deploying..."
      - name: Force failure
        run: exit 1

  notify-success:
    needs: 
      - build 
      - deploy
    if: success()
    # if: failure()
    # if: always()
    # if: cancel()
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: https://discord.com/api/webhooks/1421350407082610699/xGxWYcF8TJcRvnpKb7QnDAyrgzyQEfMgXoQeM2f8JCWVVdwzyYCbcOIbavd1F8Lvvon8
          # DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'build success'
          
  notify-failure:
    needs: 
      - build 
      - deploy
    if: failure()
    # if: always()
    # if: cancel()
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: https://discord.com/api/webhooks/1421350407082610699/xGxWYcF8TJcRvnpKb7QnDAyrgzyQEfMgXoQeM2f8JCWVVdwzyYCbcOIbavd1F8Lvvon8
          # DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'build failure'
