name: Deploy React
on: 
  push:
    branches:
      # - home
      - main
      - features/**
      - "!features/authen"
  workflow_dispatch:
  pull_request:
    types:
      - opened
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use repo variable
        run: echo "API URL:${{ vars.API_VARIABLE }}"
      - name: Use repo secrets
        run: echo "API URL:${{ secrets.API_SECRET }}"
      - name: Clone repo
        uses: actions/checkout@v5
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.18
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}  
      - name: Install Dependencies
        run: bun i
      - name: Build Project
        run: bun run build
      - name: List files
        run: ls -l dist
      - name: Upload dist folder
        uses: actions/upload-artifact@v4
        with:
          name: dist-folder
          path: dist/

  deploy:
    if: github.ref == 'refs/heads/main' 
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download dist folder
        uses: actions/download-artifact@v4
        with:
          name: dist-folder
      - name: List all files
        run: ls -R
      - name: Deploy
        run: echo "Deploying..."