name: Matrix
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bun-version: [1.2.0, 1.2.18, 1.2.16]
        browser: [ "firefox", "chrome", "safari"]
    steps:
      - name: Print Bun version
        run: echo "${{ matrix.bun_version }} - ${{ matrix.browser }}"